-- Generated from lib/videos.ts. Run after schema.sql. Existing IDs are preserved.
insert into public.videos (id,title,channel,handle,avatar,thumbnail,category,views,uploaded,duration,description,subscribers,likes,verified,is_short,video_url,sort_order) values
  ('v1', '30 hari hidup lebih produktif: kebiasaan kecil yang mengubah segalanya', 'Ruang Tumbuh', '@ruangtumbuh', '#8759c8', '/thumbnails/v1.jpg', 'Lifestyle', '1,2 jt x ditonton', '2 hari lalu', '18:24', 'Aku mencoba rutinitas baru selama 30 hari. Dari bangun pagi sampai mengatur waktu kerja, ini hal-hal kecil yang ternyata membuat perbedaan besar. Semoga perjalanan ini bisa jadi inspirasi buat kamu juga!', '842 rb', '34 rb', true, false, '/demo-video.mp4', 0),
  ('v2', 'Setup meja kerja impian 2026 — minimalis, nyaman, dan rapi', 'Naufal Tech', '@naufaltech', '#375a94', '/thumbnails/v2.jpg', 'Teknologi', '486 rb x ditonton', '5 hari lalu', '14:08', 'Tour lengkap meja kerja terbaru! Kita bahas monitor, keyboard, pencahayaan, dan beberapa aksesori favorit yang bikin kerja lebih nyaman.', '312 rb', '12 rb', true, false, '/demo-video.mp4', 1),
  ('v3', 'Jelajah Jepang sendirian: 7 hari yang nggak akan terlupakan', 'Jalan Bareng Aya', '@jalanbarengaya', '#e68a68', '/thumbnails/v3.jpg', 'Travel', '928 rb x ditonton', '1 minggu lalu', '24:16', 'Dari jalanan Tokyo yang ramai sampai sudut kecil yang tenang. Ini cerita perjalanan solo pertamaku di Jepang.', '576 rb', '27 rb', true, false, '/demo-video.mp4', 2),
  ('v4', 'Masak pasta creamy cuma 15 menit, rasanya seperti di restoran!', 'Dapur Naya', '@dapurnaya', '#c57842', '/thumbnails/v4.jpg', 'Kuliner', '2,4 jt x ditonton', '3 minggu lalu', '12:35', 'Resep pasta creamy yang gampang banget dibuat di rumah. Bahan sederhana, hasilnya spesial. Semua takaran dan langkah ada di video ini.', '1,8 jt', '86 rb', true, false, '/demo-video.mp4', 3),
  ('v5', 'Playlist buat nemenin kerja dan belajar ☕ lofi & chill beats', 'Sore Sounds', '@soresounds', '#b98155', '/thumbnails/v5.jpg', 'Musik', '3,7 jt x ditonton', '1 bulan lalu', '1:02:45', 'Satu jam musik santai untuk menemani fokus, belajar, atau sekadar menikmati sore. Pakai headphone untuk pengalaman terbaik.', '224 rb', '94 rb', false, false, '/demo-video.mp4', 4),
  ('v6', 'Aku coba game paling ditunggu tahun ini... worth it nggak?', 'Raka Plays', '@rakaplays', '#584cbb', '/thumbnails/v6.jpg', 'Gaming', '734 rb x ditonton', '4 hari lalu', '28:12', 'First impression, gameplay, dan pendapat jujur setelah beberapa jam bermain. Tulis game favorit kalian di komentar ya!', '653 rb', '21 rb', true, false, '/demo-video.mp4', 5),
  ('v7', 'Belajar UI design dari nol: prinsip yang wajib kamu tahu', 'Studio Karya', '@studiokarya', '#df6685', '/thumbnails/v7.jpg', 'Desain', '193 rb x ditonton', '2 minggu lalu', '21:47', 'Panduan singkat dan praktis untuk mulai memahami UI design. Kita bahas hierarki visual, warna, tipografi, dan layout.', '147 rb', '8,4 rb', false, false, '/demo-video.mp4', 6),
  ('v8', 'Ngobrol soal karier, keberanian mulai lagi, dan menemukan arah', 'Cerita Kita', '@ceritakita', '#537a73', '/thumbnails/v8.jpg', 'Podcast', '654 rb x ditonton', '6 hari lalu', '58:31', 'Episode kali ini ngobrol santai tentang karier, rasa takut memulai, dan bagaimana menemukan arah di tengah perubahan.', '481 rb', '18 rb', true, false, '/demo-video.mp4', 7),
  ('v9', 'Hidden gems di Bali yang masih sepi wisatawan', 'Jalan Bareng Aya', '@jalanbarengaya', '#e68a68', '/thumbnails/v9.jpg', 'Travel', '312 rb x ditonton', '2 minggu lalu', '19:54', 'Beberapa tempat cantik di Bali yang belum banyak orang tahu. Simpan videonya untuk rencana perjalananmu berikutnya!', '576 rb', '9,8 rb', true, false, '/demo-video.mp4', 8),
  ('v10', 'Bikin website portfolio yang bikin recruiter berhenti scroll', 'Naufal Tech', '@naufaltech', '#375a94', '/thumbnails/v10.jpg', 'Teknologi', '245 rb x ditonton', '1 minggu lalu', '32:18', 'Kita bikin portfolio sederhana yang cepat, responsif, dan punya detail visual yang memorable.', '312 rb', '11 rb', true, false, '/demo-video.mp4', 9),
  ('v11', 'Rutinitas pagi yang realistis (tanpa bangun jam 5!)', 'Ruang Tumbuh', '@ruangtumbuh', '#8759c8', '/thumbnails/v11.jpg', 'Lifestyle', '854 rb x ditonton', '3 hari lalu', '16:09', 'Rutinitas pagi sederhana yang bisa disesuaikan dengan ritme hidup kamu sendiri. Nggak harus sempurna, yang penting konsisten.', '842 rb', '25 rb', true, false, '/demo-video.mp4', 10),
  ('v12', 'Cara belajar skill baru lebih cepat menurut sains', 'Satu Persen Lagi', '@satupersenlagi', '#bd645c', '/thumbnails/v12.jpg', 'Belajar', '1,1 jt x ditonton', '1 bulan lalu', '22:42', 'Strategi belajar yang didukung riset dan bisa langsung dicoba. Mulai dari active recall sampai membuat jadwal latihan yang masuk akal.', '1,2 jt', '39 rb', true, false, '/demo-video.mp4', 11),
  ('s1', 'Momen paling cantik di jalanan Tokyo 🌸', 'Jalan Bareng Aya', '@jalanbarengaya', '#e68a68', '/thumbnails/v3.jpg', 'Travel', '1,8 jt x ditonton', '1 hari lalu', '0:42', 'Sekilas perjalanan sore yang tidak terlupakan di Tokyo.', '576 rb', '62 rb', true, true, '/demo-video.mp4', 12),
  ('s2', 'Pasta creamy anti gagal dalam 40 detik 🍝', 'Dapur Naya', '@dapurnaya', '#c57842', '/thumbnails/v4.jpg', 'Kuliner', '3,2 jt x ditonton', '2 hari lalu', '0:38', 'Resep super cepat untuk makan malam yang istimewa.', '1,8 jt', '104 rb', true, true, '/demo-video.mp4', 13),
  ('s3', 'Detail kecil yang bikin setup meja makin nyaman', 'Naufal Tech', '@naufaltech', '#375a94', '/thumbnails/v2.jpg', 'Teknologi', '874 rb x ditonton', '3 hari lalu', '0:55', 'Satu perubahan sederhana untuk ruang kerja yang lebih nyaman.', '312 rb', '27 rb', true, true, '/demo-video.mp4', 14),
  ('s4', 'Pagi pelan-pelan juga boleh ☕', 'Ruang Tumbuh', '@ruangtumbuh', '#8759c8', '/thumbnails/v11.jpg', 'Lifestyle', '521 rb x ditonton', '5 hari lalu', '0:31', 'Pengingat kecil untuk menikmati pagi tanpa terburu-buru.', '842 rb', '19 rb', true, true, '/demo-video.mp4', 15)
on conflict (id) do nothing;
